# helm upgrade -i flagger flagger/flagger --wait \
# --namespace linkerd \
# --set crd.create=false \
# --set metricsServer=http://linkerd-prometheus:9090 \
# --set meshProvider=linkerd
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: linkerd
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: flagger
  chart:
    git: git@github.com:weaveworks/flagger
    ref: refs/tags/0.22.0
    path: charts/flagger
    # repository: https://flagger.app
    # name: flagger/flagger
    # version: 0.22.0
  values:
    crd.create: "false"
    metricsServer: http://linkerd-prometheus:9090
    meshProvider: linkerd
