---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: www
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:dev-*
spec:
  releaseName: www
  chart:
    git: git@github.com:dellintosh/gitops-helm-workshop
    ref: master
    path: cluster/charts/www
  values:
    image:
      repository: 277866474112.dkr.ecr.us-east-1.amazonaws.com/www
      tag: dev-aecaa7b
    service:
      enabled: false
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:80;
          proxy_hide_header l5d-remote-ip;
          proxy_hide_header l5d-server-id;
      path: /
      hosts:
      - www.eks01.coinlion.io
